### PR TITLE
.Net Standard update

### PR DESCRIPTION
**Pull request by ToddBertaOldham**
I figured I'd go ahead and create a pull request for my [issue](https://github.com/ioctlLR/NVorbis/issues/15). I updated the NVorbis library to the new [.csproj format](http://blogs.microsoft.co.il/iblogger/2017/04/05/easily-supporting-multiple-target-frameworks-tfms-with-vs2017-and-nuget/). The format is configured with both [.Net Standard 2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) and .Net Framework 3.5. All other projects have not been changed including OpenTKSupport. Some work maybe necessary to update the Nuget package since the NVorbis library targets multiple frameworks. However, I did see the option to generate the Nuget package automatically in the package settings of the project. That might be worth looking into. More work could be done to target earlier versions of .Net Standard as I stated in my issue. However, this is certainly a start for being fully compatible with additional frameworks such as UWP and .Net Core. Also I removed the old NAudio test since it relied on the now removed NAudioSupport library. Not sure if you want to update that instead using the [new library](https://github.com/naudio/Vorbis).

### CODE REVIEW

**Comment by feliwir** [comment]
Please merge

**Comment by ToddBertaOldham** [comment]
I double checked everything so I'm going to go ahead and merge this. I will update the NuGet package once I have access.

**Comment by ioctlLR** [comment]
Cool.  Thanks!

And don't worry about me reviewing things...  As much as I'd like to be
more involved, time constraints won't let me.

**Comment by ioctlLR** [comment]
@ToddBertaOldham, what is your NuGet username?  I'll add you as a package owner.

**Comment by ToddBertaOldham** [comment]
Yeah, I figured there wasn't a point in having you review things after I posted. I know you're busy and you gave me write access for that reason, so I went and merged it. My username on NuGet is [ToddBertaOldham](https://www.nuget.org/profiles/ToddBertaOldham).

**Pull request merged**
